
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ricki Millones
 */
public class NewJFrame extends javax.swing.JFrame {
   private String[][] imageInfo;
    private int currentImageIndex;
    
    public NewJFrame() {
        initComponents();
        imageInfo = new String[][]{
           {"Primera Imagen "},
            {"src/imagenes/Captura1.PNG", "1.Al iniciar una partida el usurio 1 necesitara elegir si \"villanos\" o \"heroes\". "},
             {"src/imagenes/Captura2.PNG", "2.La partida la comenzaran los heroes.  "},
             {"src/imagenes/Captura3.PNG", "3.Existen 12 tipos de piezas desde el rango 1 al 10, la bandera \"Planeth Earth\" y bombas \"Nova blast\" o \"Pumpkin Bomb\". "},
              {"src/imagenes/Captura4.PNG", "4.Las Piezas de Rango 2 se pueden movilizar y atacar cuanatas casilas deseen. "},
               {"src/imagenes/Captura5.PNG", "5.Las Piezas que no sean de rango 2 se pueden movilizar y atacar solamente 1 casilla."},
              {"src/imagenes/Captura6.PNG", "6.Existen dos zonas prohibidas las cuales no estan permitido colocar piezas sobre ellas."},
               {"src/imagenes/Captura7.PNG", "7.Las piezas del contrincante estaran ocultas hasta que sea su turno y viceversa. "},
                {"src/imagenes/Captura8.PNG", "8.Al atacar ganara la pieza de mayor rango. "},
                 {"src/imagenes/PersonajesEliminados.PNG", "9.Al lado Derecho se mostratan tus personajes eliminados. "},
                 {"src/imagenes/Captura-9-2.PNG", "10.Toda pieza que intente atacr una bomba sera eliminada automaticamnete a excepcion de las de Rango 3.  "},
                  {"src/imagenes/Captura10-2.PNG", "11.Ganara la partida quien logre capturar la bandera del contrincante. "},
                   {"src/imagenes/Captura11.PNG", "12.Tambien se ganara si el contrincante decide rendirse. "},
                    {"src/imagenes/Captura12.PNG", "13.El ganador obtendra 3 puntos y el perder 0."},
            // Añade más rutas de imágenes y textos aquí
        };
        
        
    }
    
    

    private void displayImage() {
        String imagePath = imageInfo[currentImageIndex][0];
        String text = imageInfo[currentImageIndex][1];

        ImageIcon imageIcon = new ImageIcon(imagePath);
        imageLabel.setIcon(imageIcon);
        textLabel.setText(text);
    }
    
      private void showPreviousImage() {
      
        if (currentImageIndex > 0) {
            currentImageIndex--;
            displayImage();
        }
    }

    private void showNextImage() {
      
        if (currentImageIndex < imageInfo.length - 1) {
            currentImageIndex++;
            displayImage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        textLabel.setText("a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jButton1)
                .addGap(100, 100, 100)
                .addComponent(jButton2)
                .addGap(113, 113, 113)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(29, 29, 29)
                .addComponent(textLabel)
                .addGap(36, 36, 36)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         showNextImage();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         showPreviousImage();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
